apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - datasources.yaml
  - dashboards-provider.yaml
  - deployment.yaml

configMapGenerator:
  - name: grafana-k6-dashboard
    files:
      - k6-dashboard.json
      - ags-control-panel-dashboard.json
      - ags-data-plane-dashboard.json
